9-1認識Numpy的陣列

In [26]:
#1
import numpy as np
#1-a
a = np.array([[1.2],[ 4.3],[ 5.4],[6.7]])
print(a.shape)
print(a.ndim)
print(a.size)

#1-b
b = np.array([[1.2, 4.3, 5.4 , 6.7]])
print(b.shape)
print(b.ndim)
print(b.size)

#1-c
a = np.array([[5]])
print(a.shape)
print(a.ndim)
print(a.size)

#1-d
np.tile([ [4],[2],[5]],(1,4))


(4, 1)
2
4
(1, 4)
2
4
(1, 1)
2
1


array([[4, 4, 4, 4],
       [2, 2, 2, 2],
       [5, 5, 5, 5]])

In [48]:
#2
# a = np.array([[4,7,8,12]])
# print(a)
# #2-a

#2-a
a = np.array([[4,7],[8,12]])

print(a)

#2-b
b = np.array([[7.4],[6.7],[2.0]] ,dtype=float)
print(b)

#2-c
c = np.array([[7,4],[6,7],[9,-5]])
print(c)

[[ 4  7]
 [ 8 12]]
[[7.4]
 [6.7]
 [2. ]]
[[ 7  4]
 [ 6  7]
 [ 9 -5]]


In [67]:
#3
a = np.zeros((3,4),dtype=int)

b = np.ones((3,4),dtype=int)

np.tile([a,b],(1,1))

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [73]:
#4
print("因為np.array(5).ndim 中的5是純量，純量的維度為零")
print("因為沒賦予5.ndim中的5 numpy.array屬性")

因為np.array(5).ndim 中的5是純量，純量的維度為零
因為沒賦予5.ndim中的5 numpy.array屬性


In [76]:
#5
np.arange(0,1.01,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [78]:
#6
np.zeros((2,3,4),dtype="uint8")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

In [95]:
#7
a = np.random.rand(2,3)

print(a)

[[0.01586025 0.37127269 0.66079606]
 [0.33087351 0.39184079 0.06832817]]


In [99]:
#8
rg = np.random.default_rng(seed = 200)

rg.choice(range(1,21),10,replace=False)

array([17, 19,  1, 16,  8,  4, 18, 10, 12,  6])

In [142]:
#9
a =np.array([[0,1,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15]])
b = [0,1,3,4,5,6,7,8,9,10,11,12,13,14,15]
rg = np.random.default_rng(seed = 20)
#9-a
print(rg.choice(b,8,replace=False))
#9-b
print(rg.choice(b,10,axis=0,replace=True))
# #9-c
print(rg.choice(a,2,axis=0,replace=False))

[ 1 15  6 11  8  4 10  3]
[15 14 11 14  7  9 10  7  5 11]
[[ 6  7  8  9 10]
 [ 0  1  3  4  5]]


9-2陣列元素的提取

In [161]:
#10
a=np.array([23,67,54,26,92,88,53])
#10-a
print(a[0],a[2],a[5])
#10-b
print(a[-1:-4:-1])
#10-c
rule = a>50
print(a[rule])
#10-d
rule2 = a%2==1
print(a[rule2])
#10-e
rule2 = a%2==0
print(a[rule2])
#10-f
print(a[::-1])
#10-g
print(a[4:1:-1])

23 54 88
[53 88 92]
[67 54 92 88 53]
[23 67 53]
[54 26 92 88]
[53 88 92 26 54 67 23]
[92 26 54]


In [192]:
#11
a=np.arange(20).reshape((4,5))
print(a)
#11-a
print()
print(a[0:4,2])
print(a[0:4,4])
#11-b
print()
print(a[0:3])
#11-c
print()
print(a[::-1])
#11-d
print()
rule3=a%3==0
print(a[rule3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[ 2  7 12 17]
[ 4  9 14 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]

[ 0  3  6  9 12 15 18]
